<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sabina Oktafiani">
<meta name="dcterms.date" content="2023-01-20">

<title>ANALISIS PENGARUH KUANTITAS TERHADAP NILAI EKSPOR KOPI KE NEGARA CHINA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ANALISIS PENGARUH KUANTITAS TERHADAP NILAI EKSPOR KOPI KE NEGARA CHINA</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sabina Oktafiani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Kebutuhan akan produk ekspor di seluruh dunia telah meningkat pesat dalam beberapa tahun terakhir. Salah satu produk ekspor yang paling banyak dicari adalah kopi. Kopi telah menjadi salah satu produk ekspor yang paling populer dan paling menguntungkan di dunia. Negara China adalah salah satu tujuan utama untuk ekspor kopi. Dalam 15 tahun terakhir, meskipun jumlah produksi kopi semakin meningkat, namun pangsa ekpor kopi Indonesia semakin menurun, dari 5,1% pada 2005, menjadi 3,8% pada tahun 2015 (Rosiana et.al, 2017). Penurunan tersebut seiring dengan pergeseran tujuan ekspor kopi Indonesia. Pada tahun 2005, Amerika Serikat, Jepang, dan Jerman menjadi tujuan utama ekspor kopi Indonesia, namun hari ini turun, menjadi sekitar sepertiga dari total ekspor kopi Indonesia (Jamil, 2019). Sebagian alasannya adalah penurunan daya saing akibat diterapkannya peraturan keamanan makanan yang lebih ketat di Amerika Serikat, UE dan Jepang, seiring dengan penerapan ekonomi hijau dan prinsip keberlanjutan SDGs. Sebagai contoh di Jerman, peraturan terkait SDGs ini berkontribusi pada penurunan impor sebesar 30 juta kilogram sejak tahun 2009. Trend tersebut telah menggeser tujuan ekspor kopi Indoensi untuk memenuhi permintaan yang lebih kuat dari pasar negara ASEAN, seperti Malaysia dan Thailand, serta ekonomi regional utama lainnya seperti Italia, Rusia dan Mesir (OECD/ERIA, 2018). Namun tren terbaru, menunjukkan ekspor ke Italia meningkat secara signifikan, karena pembuat kopi dan penjual kopi (Cafe) khas Italia menggunakan campuran Robusta Indonesia yang mengandung paling sedikit pestisida dibandingkan produk kopi negara lainnya (TPSA, 2017).</p>
<p>Kewirausahaan petani kopi sebagai UMKM yang berperan berkontribusi langsung pada laju pertumbuhan ekonomi, sejalan dengan teori yang dikembangkan oleh Kirzner, Hausmann dan Rodrik, bahwa wirausahawan adalah agen penting dalam menggerakkan proses penemuan yang diperlukan untuk menghasilkan pertumbuhan dan menyeimbangkan pasar (Patrick, 2017). Sebagai contoh, kekuatan wirausaha UMKM yang menjadi unggulan negaranya masing-masing, seperti UMKM garmen di Bangladesh, perangkai bunga di Kolombia, dan pemrograman teknologi informasi (TI) di India. Teori ini mendukung gagasan bahwa kewirausahaan menghasilkan pertumbuhan dengan menciptakan peluang ekonomi baru, merangsang persaingan dan mendorong peningkatan produktivitas dalam suatu ekonomi (Irawan, 2020). Fenomena jaringan produksi atau rantai nilai (GVC) berdasarkan pada teori fragmentasi, yang dikenal sebagai pembagian produksi lintas-batas pasar, daerah, dan negara. Teori fragmentasi berfokus pada berbagai lokasi proses produksi dan lokasi assembling sebagai intinya (Kano, Tsang, &amp; Yeung, 2020)</p>
<p>Meskipun kopi telah menjadi salah satu produk ekspor yang paling menguntungkan di dunia, ada beberapa masalah yang terkait dengan ekspor kopi ke Negara China. Masalah utama yang dihadapi adalah bahwa nilai ekspor kopi ke Negara China sangat bergantung pada kuantitas produk yang diekspor. Dengan meningkatnya persaingan antar produsen kopi di dunia, produsen kopi di seluruh dunia berjuang untuk meningkatkan kuantitas produknya untuk meningkatkan nilai ekspor kopi ke Negara China. Namun, masih tidak jelas bagaimana kuantitas produk berpengaruh terhadap nilai ekspor kopi ke Negara China. Hal ini menjadi masalah yang harus dipecahkan karena kuantitas produk yang diekspor dapat mempengaruhi nilai ekspor kopi ke Negara China. Oleh karena itu, penting untuk menganalisis pengaruh kuantitas terhadap nilai ekspor kopi ke Negara China agar dapat meningkatkan nilai ekspor kopi ke Negara China. Oleh karena itu, tujuan penelitian ini adalah untuk menganalisis pengaruh kuantitas terhadap nilai ekspor kopi ke Negara China.</p>
<p>Penelitian ini akan menggunakan data historis dan survei untuk mengumpulkan data yang diperlukan. Penelitian ini juga akan menganalisis bagaimana kuantitas produk yang diekspor dapat mempengaruhi nilai ekspor kopi ke Negara China. Penelitian ini akan menggunakan analisis statistik untuk menganalisis data yang diperoleh. Penelitian ini akan memberikan wawasan kepada produsen kopi tentang bagaimana meningkatkan kuantitas produk mereka untuk meningkatkan nilai ekspor kopi ke Negara China. Hasil penelitian ini juga akan memberikan informasi penting untuk membantu produsen kopi meningkatkan nilai ekspor kopi mereka ke Negara China.</p>
<p>Metodologi yang akan digunakan dalam penelitian ini adalah analisis regresi. Analisis regresi akan digunakan untuk menentukan hubungan antara variabel-variabel yang berpengaruh terhadap nilai ekspor kopi. Selain itu, penelitian ini juga akan menganalisis bagaimana faktor-faktor ekonomi, seperti harga, inflasi, dan permintaan, dapat mempengaruhi nilai ekspor kopi ke Negara China. Hasil penelitian ini akan membantu produsen kopi untuk memahami bagaimana meningkatkan kuantitas produk mereka untuk meningkatkan nilai ekspor kopi ke Negara China. Hasil penelitian ini juga akan memberikan informasi penting untuk membantu produsen kopi membuat keputusan yang tepat untuk meningkatkan nilai ekspor kopi mereka ke Negara China.</p>
</section>
<section id="batasan-masalah" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="batasan-masalah"><span class="header-section-number">1.2</span> Batasan Masalah</h3>
<p>Berdasarkan identifikasi masalah yang sudah dijelaskan, maka penelitian ini dibatasi agar terfokus pada pengaruh kuantitas terhadap nilai ekspor kopi ke negara china. Dalam penelitian ini subyek konsumen dibatasi pada nilai ekspor yang di ekspor hanya ke negara china.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan latar belakang dan identifikasi masalah yang sudah dijelaskan diatas, maka rumusan masalah untuk penelitian ini adalah apakah pengaruh kuantitas terhadap nilai ekspor kopi ke negara china?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
</section>
</section>
<section id="tujuan" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="tujuan"><span class="header-section-number">2</span> Tujuan</h2>
<p>Berdasarkan rumusan masalah tersebut, tujuan penelitian ini adalah untuk mengetahui seberapa pengaruh kuantitas terhadap nilai ekspor kopi ke negara china.</p>
</section>
<section id="manfaat" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="manfaat"><span class="header-section-number">3</span> Manfaat</h2>
<p>Pada penulisan penelitian ini, peneliti berharap bahwa karya ini dapat memberikan manfaat secara akademis dan praktis. Berikut manfaat dalam penelitian ini: a. Manfaat akademis Hasil dari penelitian ini dapat dijadikan bahan referensi yang berguna bagi penelitian selanjutnya khusus tentang pengaruh kuantitas terhadap nilai ekspor kopi ke negara china. b. Manfaat praktis ● Bagi peneliti Penelitian ini diharapkan dapat menambah wawasan peneliti dalam bidang bisnis internasional, khususnya ekspor dan impor. ● Bagi masyarakat Penelitian ini diharapkan dapat memberikan informasi berkaitan dengan pengaruh kuantitas terhadap nilai ekspor kopi ke negara china dan referensi dalam pengembangan strategi ekspor dan impor.</p>
<section id="package" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="package"><span class="header-section-number">3.1</span> Package</h3>
<p>Ini tidak wajib ada di packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">4</span> Studi pustaka</h2>
<p>2.1 Daya Saing Daya saing merupakan kemampuan suatu daerah dibanding daerah lain dalam menetapkan strategi yang tepat untuk meningkatkan kesejahteraan masyarakat. Dengan kata lain, daya saing adalah interaksi yang kompleks antara faktor input (sebagai faktor utama pembentuk daya saing) dan output (inti dari kinerja perekonomian, yaitu meningkatkan kesejahteraan masyarakat) yang ada di daerah masing-masing. Analisis daya saing dihitung dengan menggunakan konsep RCA dan EPD. 1. Teori Revealed Comparative Advantage (RCA) Revealed Comparative Advantage (RCA) digunakan untuk menganalisis keunggulan komparatif suatu komoditi dalam suatu negara (Kemendag, 2008). Dari nilai RCA dapat diketahui bagaimana daya saing suatu produk apakah daya saingnya rendah atau tinggi. Jika semakin tinggi nilai RCA, berarti daya saingnya semakin tinggi, dan sebaliknya. Batasan nilai daya saing. 2. Teori Export Product Dynamics (EPD) Untuk mengetahui posisi pangsa pasar dapat dilakukan menggunakan alat analisis Export Product Dynamics (EPD) berdasarkan dua indikator utama, yaitu peningkatan pangsa pasar ekspor negara dan peningkatan pangsa pasar produk. Menurut Tarman dkk, 2011 melalui analisis ini diperoleh empat posisi pangsa pasar yang berbeda, yaitu: a. Rising Star: terjadi peningkatan pangsa pasar ekspor negara dan pangsa pasar produk tertentu di perdagangan dunia. b. Lost Opportunity: terjadi penurunan pangsa pasar ekspor negara, tapi terjadi peningkatan pangsa pasar produk tertentu di perdagangan dunia. c.&nbsp;Falling Star: terjadi peningkatan pangsa pasar ekspor negara, tapi terjadi penurunan pangsa produk tertentu di perdagangan dunia. d.&nbsp;Retreat: terjadi penurunan pangsa pasar ekspor negara dan pangsa pasar produk tertentu di perdagangan dunia.</p>
<p>2.2 Faktor-Faktor yang Mempengaruhi Ekspor Ekspor adalah seluruh benda dan jasa yang dijual ke negara lain ditambah dengan jasa-jasa yang diselenggarakan negara tersebut berupa pengangkutan, permodalan, dan hal-hal lainnya yang menunjang ekspor tersebut. Terjadinya ekspor disebabkan karena adanya kelebihan penawaran (supply) domestik, dimana akibat harga domestic relatif lebih rendah bila dibandingkan harga negara lain. Permintaan terhadap volume ekspor kopi ditentukan oleh gross domestic product (GDP), nilai tukar riil, dan harga ekspor kopi. GDP merupakan merupakan pendapatan rata-rata penduduk di suatu negara pada waktu tertentu yang dapat digunakan sebagai salah satu indikator dalam mengukur tingkat konsumsi atau kemampuan daya beli suatu negara atas barang dan jasa tertentu. Nilai tukar riil (real exchange rate) merupakan harga suatu mata uang dalam satuan mata uang asing atau jumlah mata uang suatu negara asing yang harus dibayarkan untuk mendapatkan satu unit uang domestik Harga didefinisikan sebagai suatu nilai yang diberikan dalam menukarkan barang atau jasa.</p>
<p>2.3 Kerangka Penelitian Komoditas kopi merupakan salah satu komoditas unggulan dan menjadi pemasok devisa negara di subsektor perkebunan, selain itu juga sebagai sumber pendapatan bagi petani kopi. Dalam upaya peningkatan daya saing juga terdapat beberapa hambatan yang dihadapi salah satunya yaitu produktivitas kopi yang rendah. Produktivitas kopi Indonesia jauh lebih rendah dibandingkan dengan Brazil, Vietnam dan Kolombia. Analisis daya saing dilakukan dengan menggunakan metode Revealed Comparative Advantage (RCA) dan Export Product Dynamic (EPD), sedangkan untuk mengetahui faktor-faktor yang mempengaruhi volume ekspor kopi Indonesia menggunakan empat variabel yaitu GDP, nilai tukar riil, harga ekspor dan harga kopi dunia. Hipotesis sebagai berikut : 1. Nilai RCA kopi Indonesia diduga lebih dari satu (RCA &gt; 1), artinya Indonesia memiliki keunggulan komparatif pada kopi sehingga memiliki daya saing kuat di pasar internasional 2. GDP, nilai tukar riil, harga ekspor dan harga kopi dunia diduga berpengaruh positif terhadap volume ekspor kopi Indonesia.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">5</span> Metode penelitian</h2>
<p>3.1 Data Data yang digunakan dalam penelitian ini adalah data sekunder selama periode Tahun 2011 – 2021 yang mencakup volume dan nilai ekspor kopi Arabika Indonesia, nilai ekspor total dari Indonesia, nilai ekspor kopi dunia, nilai ekspor total dunia, nilai tukar rupiah terhadap dolar AS, dan pertumbuhan ekonomi Indonesia. Data bersumber dari Badan Pusat Statistik dan trade map. Untuk menganalisis pengaruh kuantitas terhadap nilai ekspor kopi ke negara china digunakan formula sebagai berikut: Laursen dalam Imelda (2017). RCA = 𝐗𝒊 𝒊𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 ∑ 𝚾𝒊 𝑰𝒏𝒅𝒐𝒏𝒆𝒔𝒊𝒂 / 𝐗𝒊 𝒘𝒐𝒓𝒍𝒅 ∑ 𝚾𝒊 𝒘𝒐𝒓𝒍𝒅 Dimana: RCA : Revealed Comparative Advantage untuk komoditi i X𝑖 𝑖𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai Ekspor komoditas dari Indonesia ∑ Χ𝑖 𝐼𝑛𝑑𝑜𝑛𝑒𝑠𝑖𝑎 : Nilai ekspor total dari Indonesia X𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor produk dunia ∑ Χ𝑖 𝑤𝑜𝑟𝑙𝑑 : Nilai ekspor total dunia</p>
<p>Apabila nilai RCA yang didapat lebih besar dari satu maka dapat dikatakan Indonesia memiliki keunggulan komparatif dalam komoditi yang terkait dan mempunyai dayasaing yang kuat. Apabila nilai RCA kurang dari satu maka Indonesia tidak memiliki keunggulan komparatif terhadap komoditi tersebut atau komoditi tersebut dayasaingnya lemah. Semakin tinggi nilai RCA-nya, semakin kuat dayasaingnya (Balassa dalam Ratnawati, 2011). Untuk menganalisis pengaruh produksi kopi, pertumbuhan ekonomi dan kurs terhadap volume ekspor kopi Arabika di pasar internasional menggunakan metode analisis regresi linier berganda dengan pendekatan model Ordinary Least Square (OLS) atau metode kuadrat terkecil biasa, dengan persamaan sebagai berikut: 𝑳𝒐𝒈𝑽𝒌 = 𝜷𝟎 + 𝜷𝟏𝑳𝒐𝒈𝑷𝑲 + 𝜷𝟐𝑳𝒐𝒈𝑲𝑼𝑹𝑺 + 𝜷𝟑𝑳𝒐𝒈𝑷𝑫𝑩 + 𝒆𝒊</p>
<p>Dimana : 𝐿𝑜𝑔𝑉𝑘 :Volume ekspor kopi 𝐿𝑜𝑔𝛽0 : Konstanta 𝐿𝑜𝑔𝑃𝐾 : Produksi Kopi Indonesia 𝐿𝑜𝑔𝐾𝑈𝑅𝑆 : Nilai tukar rupiah terhadap dollar AS 𝐿𝑜𝑔𝑃𝐷𝐵 : Pertumbuhan ekonomi Indonesia 𝛽1𝛽2 𝛽3 : Koefisien regresi variabel 𝑃𝐾, 𝑃𝐸,𝐾𝑈𝑅𝑆 𝑒𝑖 : Error term</p>
<section id="data" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="data"><span class="header-section-number">5.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>X</th>
<th>Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2.091</td>
<td>18.670</td>
</tr>
<tr class="even">
<td>2.072</td>
<td>17.096</td>
</tr>
<tr class="odd">
<td>1.580</td>
<td>12.431</td>
</tr>
<tr class="even">
<td>1.115</td>
<td>11.342</td>
</tr>
<tr class="odd">
<td>1.382</td>
<td>13.097</td>
</tr>
<tr class="even">
<td>2.081</td>
<td>17.923</td>
</tr>
<tr class="odd">
<td>2.295</td>
<td>25.093</td>
</tr>
<tr class="even">
<td>1.747</td>
<td>16.512</td>
</tr>
<tr class="odd">
<td>1.430</td>
<td>12.792</td>
</tr>
<tr class="even">
<td>1.286</td>
<td>12.289</td>
</tr>
</tbody>
</table>
<p>penelitian ini menggunakan data hubungan antara variabel independen dan variabel lainnya, antara kuantitas ekspor dengan nilai ekspor kopi ke china</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#impor dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'CONTOH.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
      X     Y
  &lt;dbl&gt; &lt;dbl&gt;
1  2091 18670
2  2072 17096
3  1580 12431
4  1115 11342
5  1382 13097
6  2081 17923</code></pre>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">5.2</span> Metode analisis</h3>
<p>Metode analisis yang digunana yaitu regresi. regresi disebut juga dengan Ordinary Least Square (OLS). Digunakan untuk mencari parameter yang menghubungkan dua variabel. analisis univariat adalah analisis data secara serentak dimana data yang diamati hanya memiliki satu variabel dependen (variabel tidak bebas) pada setiap objek yang diamati. <span class="math display">\[
Yi=β0+β1Xi+μi
Y disebut juga variabel dependen
X disebut juga variabel independent
nilai Y dan X kita dapatkan dari data
β0 dan β1  disebut parameter. Nilainya kita dapat dari hasil estimasi komputer.
μ  disebut juga error term / residual. Dia bersifat independen
\]</span></p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">6</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">6.1</span> Pembahasan masalah</h3>
<p>Berikut adalah hasil dari plot x dan y. dengan x sebagai nilai(value) ekpor kopi Indonesia ke negara China dan y sebagai kuanitas ekpor kopi Indonesia ke negara China. maka didapatkan plot sebagai berikut</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"VALUE"</span>,<span class="at">ylab=</span><span class="st">"QUANTITY"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">6.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-2084.8 -1164.3    55.9   526.7  3820.3 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -415.523   2666.098  -0.156 0.880009    
X              9.450      1.523   6.207 0.000257 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1861 on 8 degrees of freedom
Multiple R-squared:  0.8281,    Adjusted R-squared:  0.8066 
F-statistic: 38.53 on 1 and 8 DF,  p-value: 0.0002575</code></pre>
</div>
</div>
<p>Data ini dilakukan untuk melihat pengaruh variabel independent yaitu value kopi dan quantity kopi secara bersama-sama terhadap variabel dependen terhadap nilai ekspor kopi ke china. berdasarkan hasil regresi diperoleh nilai F sebesar 38.53 dengan prob value sebesar 0.0002575. artinya hal tersebut berpengaruh signifikan terhadap ekspor kopi Indonesia selama periode 2011-2021. Nilai R menunjukan seberapa besar variabel independen berpengaruh terhadap variabel dependen. dapat dilihat dari koefisiensi determinasi R sebesar 80.66% sedangkan sisanya sebesar 19,34% dipengaruhi oleh variabel lain yang tidak termasuk ke dalam penelitian ini. Selanjutnya yaitu uji parsial digunakan untuk menentukan apakah variabel-variabel independen dalam persamaan regresi secara individu signifikan dalam memprediksi nilai variabel dependen. berdasarkan hal tersebut, dapat dikemukakan sebagai berikut: • Harga Kopi Dari hasil perhitungan diperoleh nilai t-hitung sebesar 0.156 dengan probabilitas sebesar 0.88 &gt; 0.1. dengan kata lain secara parsial harga kopi tidak berpengaruh signifikan terhadap ekspor kopi Indonesia ke China selama periode 2011-2021 • Kuantitas Kopi Dari hasil perhitungan diperoleh nilai t-hitung sebesar 6.027 dengan probabilitas sebesar 0.025 &lt; 0.1. dengan kata lain secara parsial bahwa kuantitas kopi berpengaruh signifikan terhadap ekspor kopi Indonesia ke China.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">7</span> Kesimpulan</h2>
<p>Hasil penelitian analisis tentang pengaruh kuantitas terhadap nilai ekspor kopi ke China telah menunjukkan bahwa kuantitas ekspor kopi berdampak signifikan terhadap nilai ekspor. Hal ini menunjukkan bahwa meningkatnya kuantitas ekspor kopi ke China dapat meningkatkan nilai ekspor secara signifikan. Dengan demikian, perlu adanya upaya untuk meningkatkan kuantitas ekspor kopi ke China agar nilai ekspor dapat ditingkatkan. Salah satu strategi untuk meningkatkan kuantitas ekspor kopi ke China adalah dengan mempromosikan produk kopi Indonesia ke pasar China. Selain itu, pemerintah dan pelaku usaha juga perlu meningkatkan kualitas produk kopi Indonesia agar dapat bersaing dengan produk kopi lainnya yang tersedia di China. Peningkatan kualitas produk kopi dapat dilakukan dengan meningkatkan kualitas biji kopi, penyulingan, dan pelatihan tenaga kerja dalam industri perkebunan kopi.</p>
<p>Pemerintah juga harus berupaya untuk menurunkan beban biaya ekspor, seperti biaya pengemasan, biaya pengiriman, dan biaya lainnya. Dengan demikian, akan meningkatkan margin keuntungan ekspor kopi Indonesia ke China. Di samping itu, pemerintah juga harus meningkatkan kesadaran masyarakat di Indonesia akan pentingnya produk kopi Indonesia sebagai produk ekspor yang menguntungkan. Pemerintah juga harus berupaya untuk meningkatkan kerja sama dengan para pengusaha di China agar produk kopi Indonesia dapat dijual di pasar China dengan harga yang kompetitif.</p>
<p>Pemerintah juga harus membuat kebijakan yang menguntungkan bagi pelaku usaha yang bergerak di bidang ekspor kopi ke China. Pemerintah juga harus mendorong perbaikan infrastruktur untuk pengiriman produk ekspor kopi ke China. Hal ini penting untuk memastikan bahwa kopi dikirim dalam kondisi yang baik. Pemerintah juga harus meningkatkan kerjasama dengan pihak China untuk memastikan bahwa produk kopi Indonesia dapat didistribusikan dengan baik ke pasar China. Dengan upaya-upaya yang disebutkan di atas, diharapkan bahwa nilai ekspor kopi ke China dapat meningkat secara signifikan. Upaya-upaya tersebut akan meningkatkan daya saing produk kopi Indonesia di pasar China sehingga akan meningkatkan nilai ekspor kopi Indonesia ke China.</p>
</section>
<section id="saran" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="saran"><span class="header-section-number">8</span> Saran</h2>
<p>Hasil penelitian analisis tentang pengaruh kuantitas terhadap nilai ekspor kopi ke China telah menunjukkan bahwa kuantitas ekspor kopi berdampak signifikan terhadap nilai ekspor. Hal ini menunjukkan bahwa meningkatnya kuantitas ekspor kopi ke China dapat meningkatkan nilai ekspor secara signifikan. Dengan demikian, perlu adanya upaya untuk meningkatkan kuantitas ekspor kopi ke China agar nilai ekspor dapat ditingkatkan. Salah satu strategi untuk meningkatkan kuantitas ekspor kopi ke China adalah dengan mempromosikan produk kopi Indonesia ke pasar China. Selain itu, pemerintah dan pelaku usaha juga perlu meningkatkan kualitas produk kopi Indonesia agar dapat bersaing dengan produk kopi lainnya yang tersedia di China. Peningkatan kualitas produk kopi dapat dilakukan dengan meningkatkan kualitas biji kopi, penyulingan, dan pelatihan tenaga kerja dalam industri perkebunan kopi.Pemerintah juga harus berupaya untuk menurunkan beban biaya ekspor, seperti biaya pengemasan, biaya pengiriman, dan biaya lainnya. Dengan demikian, akan meningkatkan margin keuntungan ekspor kopi Indonesia ke China. Pemerintah juga harus membuat kebijakan yang menguntungkan bagi pelaku usaha yang bergerak di bidang ekspor kopi ke China. Pemerintah juga harus mendorong perbaikan infrastruktur untuk pengiriman produk ekspor kopi ke China. Hal ini penting untuk memastikan bahwa kopi dikirim dalam kondisi yang baik. Pemerintah juga harus meningkatkan kerjasama dengan pihak China untuk memastikan bahwa produk kopi Indonesia dapat didistribusikan dengan baik ke pasar China. Dengan upaya-upaya yang disebutkan, diharapkan bahwa nilai ekspor kopi ke China dapat meningkat secara signifikan. Upaya-upaya tersebut akan meningkatkan daya saing produk kopi Indonesia di pasar China sehingga akan meningkatkan nilai ekspor kopi Indonesia ke China.</p>
</section>
<section id="referensi" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="referensi"><span class="header-section-number">9</span> Referensi</h2>
<p>Darmawan, A., Wibowo, L. A., &amp; Surachman, A. (n.d.). Coopetition : Jurnal Ilmiah Manajemen Penerapan Rantai Nilai Global Sebagai Strategi Peningkatan Ekspor Produk Kopi.</p>
<p>Daya, A., Made Astuti Wahyu Utami, N., Putra, D. D., &amp; Komala Dewi, R. (2018). ANALISIS DAYA SAING DAN FAKTOR-FAKTOR YANG MEMPENGARUHI EKSPOR KOPI INDONESIA DI PASAR INTERNASIONAL Competitiveness Analysis and Factors Affecting Coffee Exports in the International Market. Jurnal Manajemen Agribisnis, 6(1).</p>
<p>Kopi, E., &amp; Bali, P. (2020). Pengaruh Kurs Dollar Amerika Serikat, Inflasi, dan Harga. Jurnal Agribisnis Dan Agrowisata, 9(1). https://ojs.unud.ac.id/index.php/JAA</p>
<p>Muttoharoh, V., Rahma, ;, Candra, N. ;, Prodi, M., Pembangunan, E., Ekonomi, F., &amp; Bisnis, D. (n.d.). Daya saing dan faktor-faktor yang mempengaruhi ekspor kopi Arabika Indonesia di pasar internasional (Vol. 7, Issue 3).</p>
<p>Parwito, P. (n.d.). ESTIMATION FORECASTING MODEL FOR THE EXPORT PRICE OF INDONESIAN COFFEE.</p>
<p>Studi Agribisnis, P., &amp; Pertanian, F. (2018). E-Jurnal Agribisnis dan Agrowisata Analisis Nilai Ekspor Kopi Provinsi Bali dan Faktor-faktor yang Mempengaruhinya SAUMIA KRISNA DEVI DASI, I MADE SUDARMA, IDA AYU LISTIA DEWI. 7(2). https://ojs.unud.ac.id/index.php/JAA256</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>